version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - code-network 
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: yii2basic
        MYSQL_USER: amarilis
        MYSQL_PASSWORD: 1qaz2wsx
    ports:
        - "9906:3306"
    networks:
    - code-network 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
    networks:
    - code-network
  mailhog:
    image: mailhog/mailhog
    tty: true
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    restart: on-failure
    networks:
    - code-network
networks:
  code-network:
    driver: bridge

